### ISSUE TITLE
World Crash on load SMP

### ISSUE THREAD

**Issue by Aringarosa** [TeamDman/DiscordButInMinecraft#3]
Hello,

over at the Planetary Modpack i have encounter a annoying error.

[LINK](https://github.com/NFINIT-Development/Planetary/issues/33)

In Comment 3 i have traced it done to some degree. I hope you can someway use it.

Greetings Ringo

**Comment by TeamDman** [comment]
https://www.curseforge.com/minecraft/mc-mods/discord/files/2879457
This should have a fix, please let me know if it does or doesn't work for you!

Thanks for reporting this.

**Comment by Aringarosa** [comment]
Hello,

all prior Testing Scenarios works fine. Thanks for the fast fix!

Greetings Ringo
