### ISSUE TITLE
[BUG][1.12] Discord Integrations crashes World during launch

### ISSUE THREAD

**Issue by MBfromOK** [TeamDman/DiscordButInMinecraft#4]
**What happened?**
- Tried to launch a SSP save after building Industrial Foregoing: Plant Interactor... 
    - Game functions as expected during play time but then crashes when player attempts to load World at later date / time. (Tried 3x)
    - It seems that the Industrial Foregoing mod is causing an event that D.I. sees and **creeper explosion sound**

**What should happen?**
- World should load & spawn player

**Steps to reproduce**
- (Install Planetary Modpack)
- Place & enter a 13x13x13 Compact machine
- Plant Carrots / Potatoes
- Place a Plant Interactor (with range upgrades)
- Allow plants to mature and the Plant Interactor to start harvesting
- Save World & Exit
- Relaunch world

**Version**
-
- [X] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version 1.12.2-1.0.7

**Config file**
-# Configuration file

```
client {
    # Client ID of the Discord Rich Presence as seen in the developer portal
    S:"App ID"=<StuffNThingsGoHere>
    S:"Large Image Key"=bg
    S:"Small Image Key"=logo2
    S:"Small Image Text"=Planetary
}
```

**Crash report:**
- https://pastebin.com/3a8VQ4t9

**Additional info**

- disabling the mod (added ".disabled" to filename) allows the world to load and player to spawn.

**Comment by TeamDman** [comment]
Looks like you're using an outdated version
I'd try upgrading and seeing if the issue persists, since there have been a lot of safety checks added in newer versions.

1.0.7 => 1.0.12
https://www.curseforge.com/minecraft/mc-mods/discord/files/2879457
